### PR TITLE
bugfix for one character-suggestions

### PR DESCRIPTION
**Pull request by JanHammerschmidt**
I actually don't know if this is correct, but I think this is what it was meant ;-)

### CODE REVIEW

**Comment by eroux** [comment]
thanks a lot, it indeed looks like this was the intent!

**Comment by JanHammerschmidt** [comment]
Great 👍 
Would you be so kind to also update the pip package? ;)

Thank you!

**Comment by eroux** [comment]
Done, thanks!

**Comment by JanHammerschmidt** [comment]
Thank you!

However, now the installation (setup.py) seems to be dependent from _pypandoc_, which is (I think) a little problematic:

```
$ pip install sympound --upgrade

Collecting sympound
  Using cached https://files.pythonhosted.org/packages/d9/05/c72379a1847852407aa68ae921bf2f1d3397cff2e025f58cfe8a88584587/sympound-0.3.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\HAMMER~1\AppData\Local\Temp\pip-install-isbudg8c\sympound\setup.py", line 9, in <module>
        import pypandoc
    ModuleNotFoundError: No module named 'pypandoc'
```

**Comment by eroux** [comment]
Hmm I see... life would be so much simpler if pypi could parse markdown... anyways, pull requests welcome!

**Comment by JanHammerschmidt** [comment]
Are you using twine?

https://dustingram.com/articles/2018/03/16/markdown-descriptions-on-pypi

**Comment by eroux** [comment]
Oh great! I should upgrade my setuptools and try that

**Comment by eroux** [comment]
I just uploaded 0.4.0, can you try again?

**Comment by JanHammerschmidt** [comment]
Works great, thanks! 👍

**Pull request merged**
