### PR TITLE
belowThresholdWords is a class variable

### PR DESCRIPTION
**Pull request by JanHammerschmidt**
small bugfix ;)

### CODE REVIEW

**Comment by eroux** [comment]
thanks!

**Comment by eroux** [comment]
do you need a release now or can it wait?

**Comment by JanHammerschmidt** [comment]
no it's not urgent
Thank you!

**Comment by JanHammerschmidt** [comment]
Now it would be good to have a new version ;)

Thanks in advance!

**Comment by eroux** [comment]
done

**Pull request merged**
